[package]
name = "vartovcf"
version = "3.0.1"
authors = ["Clint Valentine <valentine.clint@gmail.com>"]
edition = "2024"
rust-version = "1.88"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/clintval/vartovcf"
repository = "https://github.com/clintval/vartovcf"
description = "Convert variants from VarDict/VarDictJava into VCF v4.2 format."
documentation = "https://github.com/clintval/vartovcf/blob/main/README.md"
categories = ["command-line-utilities", "science::bioinformatics"]
keywords = ["bioinformatics", "variant", "vcf", "vardict", "vardictjava"]

[profile.release]
lto = "fat"
codegen-units = 1

[lib]
name = "vartovcflib"
path = "src/lib/mod.rs"

[[bin]]
name = "vartovcf"
path = "src/main.rs"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.104"
bio-types = "1.0.4"
clap = { version = "4.6.7", features = ["derive"] }
csv = "1.4.0"
env_logger = "0.11.11"
log = "0.4.34"
proglog = "0.4.0"
rust-htslib = "1.0.1"
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.2.2"
file_diff = "1.0.0"
pretty_assertions = "1.4.1"
rstest = "0.27.0"
serde_test = "1.0.177"
tempfile = "3.27.0"

[lints.rust]
unsafe_code = "forbid"
